### ISSUE TITLE
Clock hangs when adding a note through STEP sequencer

### ISSUE THREAD

**Issue by mistaEmu** [izzyreal/vmpc-juce#104]
When adding a note via pad to the STEP function, the clock will freeze, rendering the PLAY and PLAY START buttons broken (sort of). The clock will hang but update to the correct value when STOP is pressed, though no audio will play.

This issue appears on the latest compiled build for Windows (and possibly others, but I haven't tested Linux or Mac)

**Comment by c3ntr0n800** [comment]
@izzyreal I am also experiencing this, both on Windows and Linux. The only workaround is to close and re-open the program when this occurs. Editing a note and copy+pasting still works though.

**Comment by izzyreal** [comment]
I tried adding notes via pads (both keyboard and mouse), in the Step Editor as well as in the main screen, but I don't see any issues so far.

Please provide version number of VMPC2000XL and steps to reproduce.

**Comment by c3ntr0n800** [comment]
The version is 0.5.14.3, here is a video showing VMPC behaving normally and behaving after adding a note in the step editor.

https://github.com/izzyreal/vmpc-juce/assets/36495548/fcc61cc3-a502-4f06-8387-7dea855548e8

**Comment by izzyreal** [comment]
Thanks, it's resolved in this commit: https://github.com/izzyreal/mpc/commit/ce34dc9ceb9f460f36b9526046b716443c6f0905

I'll try to push a release asap, but it may take a week. Let me know which platform you're on if this is blocking you, and I'll send you a preview build.
