### ISSUE TITLE
<ENVELOPE> filter ignores ATTACK value when DCY MD is set to START

### ISSUE THREAD

**Issue by mistaEmu** [izzyreal/vmpc-juce#105]
When set to START, DCY MD ignores any value set to the ATTACK parameter of a pad's envelope. This is best demonstrated by setting the ATTACK value to it's maximum level with DCY MD on START -- you won't hear any omission in initial amplitude, though the DECAY itself will work as intended.

I remember it working this way on old Linux builds and on currently on the Windows build, though I've never tested it on Mac.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/commit/8fbfd3d27d4d4d25b4ab7956a17635fdee81e33b
