### ISSUE TITLE
Build error on Fedora 40 with gcc 14.2.1

### ISSUE THREAD

**Issue by ycollet** [izzyreal/vmpc-juce#106]
I am trying to build vmpc on Fedora 40 with gcc 14.2.1 and I meet a build error:
```
In file included from /builddir/build/BUILD/vmpc-juce-0.6.1/editables/mpc/src/main/lcdgui/Screens.cpp:166:
/builddir/build/BUILD/vmpc-juce-0.6.1/deps/rapidjson/include/rapidjson/document.h: In member function â€˜rapidjson::GenericStringRef<CharType>& rapidjson::GenericStringRef<CharType>::operator=(const rapidjson::GenericStringRef<CharType>&)â€™:
/builddir/build/BUILD/vmpc-juce-0.6.1/deps/rapidjson/include/rapidjson/document.h:319:82: error: assignment of read-only member â€˜rapidjson::GenericStringRef<CharType>::lengthâ€™
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~~^~~~~~~~~~~~
```

**Comment by izzyreal** [comment]
Good find @ycollet, thanks for the report. I've updated the revision of the `rapidjson` dependency that is used in https://github.com/izzyreal/mpc from `v1.1.0` (published in 2016) to `master`. It should now include https://github.com/Tencent/rapidjson/pull/719, which fixes the issue you mentioned. Can you try to build again? You may need to wipe `editables/mpc` before doing so.

**Comment by ycollet** [comment]
First test seems to work now. I close the ticket and thanks a lot for your quick answer !
