### ISSUE TITLE
LV2 plugin version?

### ISSUE THREAD

**Issue by mxmilkiib** [izzyreal/vmpc-juce#19]
Hi! I'm wondering if you would consider an [LV2](lv2plug.in/) [plugin](https://github.com/lv2/lv2/wiki) version? There is a well enough maintained [fork of JUCE](https://github.com/DISTRHO/juce) by @falktx that supplies LV2 as a target that has been used for various projects and LV2 ports already.

**Comment by izzyreal** [comment]
Hey @mxmilkiib, I can try to build it. Can you check your URL of falkTX's fork? I'm getting a 404. Maybe you mean this? https://github.com/DISTRHO/JUCE

**Comment by mxmilkiib** [comment]
You are right, I need to delete that url from my autocomplete!

**Comment by izzyreal** [comment]
Do you know where I can find documentation? Is JUCE's CMake API supported or do I need to use the Projucer?

**Comment by falkTX** [comment]
Neither of those are supported.
I have interest on adding support for them, but I dont use neither cmake or ProJucer, so I would need some guidance.

**Comment by izzyreal** [comment]
@falkTX Thanks for latching on. Maybe I can start by matching a common build pattern for your fork. I'll take a look at the examples, and I welcome any resources you may suggest.

**Comment by dromer** [comment]
@izzyreal as I had suggested before have a look at https://github.com/DISTRHO/PawPaw

That should become a very good resource for doing cross-platform builds.
(moving to git submodels instead of conan packages would simplify things greatly as well)

**Comment by izzyreal** [comment]
PawPaw and the DISTRHO JUCE fork both look interesting, but without docs it'll be difficult to attempt to build for LV2.

**Comment by falkTX** [comment]
@dromer PawPaw will do nothing to help with LV2 wrapper. That is a step still far away.

And PawPaw was just announced, making it work for a few more plugins (plus Carla Plugin Host) has priority over making it more 3rd-party-dev friendly.

**Comment by falkTX** [comment]
> I welcome any resources you may suggest.

I think the easiest path is to add a new export option in ProJucer.
You can look at https://github.com/DISTRHO/juce/blob/main/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp#L17 to see what options are available to set.

Additionally, JucePlugin_LV2URI is required, which is basically the global ID of the plugin (as a string)

**Comment by izzyreal** [comment]
Ok, I'll keep it in mind, I might give it a shot. I'll also ask on the JUCE Discord channel if anyone has compiled to LV2.

**Comment by falkTX** [comment]
Worth noting that official JUCE devs are not willing to help in any way.
One could say even against it... at least business-wise.
So you might find some friction there.

**Comment by izzyreal** [comment]
Thanks for the heads-up. If there's no community support available, it would be cool to at some point dig into making it work myself.

**Comment by dromer** [comment]
You can always come join #lad on irc.freenode.net to talk audio dev and ask for suggestions.

**Comment by KottV** [comment]
It's quite easy to build LV2 version with cmake. For example: https://github.com/Chowdhury-DSP/ChowMatrix/
But this projects use conan. I'm not familiar with that. When I've tried **conan install ./conanfile.py** I throws this:
```
conan build conanfile.py
ERROR: conanbuildinfo.txt file not found in /media/src/src/audio/vmpc-juce
It is required for this command
You can generate it using 'conan install'
kv@Kot:~/src/audio/vmpc-juce> conan install ./conanfile.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

juce/0.1@izmar/dev: Not found in local cache, looking in remotes...
juce/0.1@izmar/dev: Trying with 'conan-center'...
ERROR: Failed requirement 'juce/0.1@izmar/dev' from 'conanfile.py (vmpc-juce/0.1)'
ERROR: Unable to find 'juce/0.1@izmar/dev' in remotes
```

**Comment by izzyreal** [comment]
@KottV Cool that you're attempting an LV2 build!

The JUCE package that Conan is looking for there comes from a small remote that I maintain, which you add manually like this:
```
conan remote add bintray-izmar https://api.bintray.com/conan/izmar/izmar-conan-dev-bintray
```

**Comment by KottV** [comment]
thnx, a little progress, but no luck yet
I guess the compiler version mismatch:
```
conan install conanfile.py
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (vmpc-juce/0.1): Installing package
Requirements
    Catch2/2.7.0@catchorg/stable from 'conan-center' - Cache
    ctoot/0.1@izmar/dev from 'bintray-izmar' - Cache
    juce/0.1@izmar/dev from 'bintray-izmar' - Cache
    moduru/0.1@izmar/dev from 'bintray-izmar' - Cache
    mpc/0.1@izmar/dev from 'bintray-izmar' - Cache
    rapidjson/1.1.0@bincrafters/stable from 'conan-center' - Cache
Packages
    Catch2/2.7.0@catchorg/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    ctoot/0.1@izmar/dev:a4878a90a3d3807f6bc8540e6e6bf84746c182b2 - Missing
    juce/0.1@izmar/dev:7e5bda016066516b835b729ff5baafa7f113b6a0 - Missing
    moduru/0.1@izmar/dev:6a05be3eb37f3997c01a464bea73e5136453ffb2 - Missing
    mpc/0.1@izmar/dev:03d5c353339801bd81a3326bfee58df3506ff60a - Missing
    rapidjson/1.1.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: ctoot/0.1@izmar/dev:a4878a90a3d3807f6bc8540e6e6bf84746c182b2
ERROR: Missing binary: juce/0.1@izmar/dev:7e5bda016066516b835b729ff5baafa7f113b6a0
ERROR: Missing binary: moduru/0.1@izmar/dev:6a05be3eb37f3997c01a464bea73e5136453ffb2
ERROR: Missing binary: mpc/0.1@izmar/dev:03d5c353339801bd81a3326bfee58df3506ff60a

juce/0.1@izmar/dev: WARN: Can't find a 'juce/0.1@izmar/dev' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=10, os=Linux
- Options:
- Dependencies:
- Requirements:
- Package ID: 7e5bda016066516b835b729ff5baafa7f113b6a0

ERROR: Missing prebuilt package for 'ctoot/0.1@izmar/dev', 'juce/0.1@izmar/dev', 'moduru/0.1@izmar/dev', 'mpc/0.1@izmar/dev'
Try to build from sources with '--build=ctoot --build=juce --build=moduru --build=mpc'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by izzyreal** [comment]
@KottV Use
```
conan install conanfile.py --build missing
```

**Comment by KottV** [comment]
Thnx, the next step :)

```
/home/kv/.conan/data/moduru/0.1/izmar/dev/build/6a05be3eb37f3997c01a464bea73e5136453ffb2/src/main/file/FileUtil.cpp:57:19: error: aggregate ‘getFreeSpace()::statfs stat’ has incomplete type and cannot be defined
   57 |     struct statfs stat;
      |                   ^~~~
/home/kv/.conan/data/moduru/0.1/izmar/dev/build/6a05be3eb37f3997c01a464bea73e5136453ffb2/src/main/file/FileUtil.cpp:59:53: error: invalid use of incomplete type ‘struct getFreeSpace()::statfs’
   59 |     if ( NULL != pw && 0 == statfs(pw->pw_dir, &stat) )
      |                                                     ^
/home/kv/.conan/data/moduru/0.1/izmar/dev/build/6a05be3eb37f3997c01a464bea73e5136453ffb2/src/main/file/FileUtil.cpp:57:12: note: forward declaration of ‘struct getFreeSpace()::statfs’
   57 |     struct statfs stat;
```
      |

**Comment by izzyreal** [comment]
I forgot that it's been a while that I pushed the `moduru`, `ctoot` and `mpc` packages to Bintray, so you're currently attempting to build against obsolete sources.

I just pushed the latest `master` for each of these. Can you `rm -rf ~/.conan/data/moduru` and the same for `ctoot` and `mpc`, then try `conan install conanfile.py --build missing` again?

**Comment by dromer** [comment]
I still think it makes 100x more sense to do this like most other projects and just use `.gitmodules` for these dependencies :#

**Comment by izzyreal** [comment]
@dromer I think you may be right, but I'd like to keep learning about Conan for now. Maybe a `.gitmodules` flow can co-exist? Feel free to start a fork, and I'm happy to help out where I can.

**Comment by KottV** [comment]
Well, I've built dependencies (was need to disable tests due compile errors), but still have bunch of errors compiling vmpc-juce.
What is Linux distro where it should build?
[errs.txt.gz](https://github.com/izzyreal/vmpc-juce/files/6073672/errs.txt.gz)

**Comment by izzyreal** [comment]
@KottV So far I've built it on Arch, Ubuntu and Debian. I also did some successful builds in Raspbian without JUCE, with Cairo and SDL2.

Taking one occurrence of each error category from your logs, we can see:

1.
```
...audiomidi/SoundRecorder.hpp:41:76: error: use of deleted function ‘circular_buffer<float>::circular_buffer(circular_buffer<float>&&)’
   41 |   circular_buffer<float> resampleBufferRight = circular_buffer<float>(10000);
```

2.
```
/media/src/src/audio/vmpc-juce/src/main/PluginProcessor.cpp:632:23: error: ‘class mpc::file::sndreader::SndReader’ has no member named ‘writeSampleData’; did you mean ‘getSampleData’?
  632 |             sndReader.writeSampleData(sound->getSampleData());
  ```

2. should be resolved by pulling latest master on `moduru`, `ctoot`, `mpc` and `vmpc-juce`.

As to 1., I don't fully understand where this error is coming from. Can you provide some info on your build environment? Linux distro, compiler, compiler version, glibc version, etc.?

I'll try to build a standalone binary in that environment.

Maybe we can work more effectively on chat. Are you on Discord? If not, we can also use IRC.

**Comment by mxmilkiib** [comment]
Might I recommend both #lad and #lv2 on freenode

**Comment by izzyreal** [comment]
@KottV I'm trying to hang out on #lad regularly, hope to see you there soon.

**Comment by izzyreal** [comment]
I manage to create a first working (in Carla) build for Ubuntu 20 ARM64 based on https://github.com/Chowdhury-DSP/DISTRHO-JUCE/tree/distrho-fork-lv2.

I pulled that branch into https://github.com/izzyreal/JUCE/tree/raw-key-events-3. Then I disabled auto-ttl generation in `extras/Build/CMake/JUCEUtils.cmake` because it somehow fails when combined with my JUCE Conan wrapper.

Tests of `mpc` are broken like @KottV mentioned. I've just disabled them on latest `master`.

To replicate a similar build:
1. `git clone https://github.com/izzyreal/JUCE && git checkout raw-key-events-lv2`
2. `cd JUCE && conan create . juce/0.1@izmar/dev`
3. `cd .. && git clone --single-branch --branch lv2 https://github.com/izzyreal/vmpc-workspace`
4. `cd vmpc-workspace && python3 build ninja`
5. `cd build && ninja -f build-Release.ninja vmpc2000xl_LV2`
6. Compile `JUCE/extras/Build/lv2_ttl_generator/lv2_ttl_generator.c` and run it against `../vmpc-juce/build/vmpc2000xl_artefacts/Release/LV2/VMPC2000XL.lv2/VMPC2000XL.so`

**Comment by dromer** [comment]
How does step `2.` work? it complains there is no `conanfile.py` in this repo.

**Comment by izzyreal** [comment]
@dromer Sorry, my mistake. Should be `juce-conan` instead of `JUCE`.

**Comment by dromer** [comment]
Where is this `juce-conan` directory?

**Comment by izzyreal** [comment]
@dromer It is created by the correct version of step 1. You can `rm -rf JUCE`.

**Comment by dromer** [comment]
Ah, derp :D

**Comment by izzyreal** [comment]
@dromer It was private, can you try again?

**Comment by dromer** [comment]
Ok! Now the only issue I have (next to `run()` not respecting my `PATH`) that the final command fails:
`CMake Error: Could not create named generator Ninja Multi-Config`

**Comment by izzyreal** [comment]
Some binaries are available here:
https://github.com/izzyreal/vmpc-binaries/raw/master/linux/ubuntu1804/VMPC2000XL-Ubuntu1804-x64-LV2.zip
https://github.com/izzyreal/vmpc-binaries/raw/master/linux/ubuntu20/VMPC2000XL-Ubuntu20-ARM64-LV2.zip

They assume you have placed the `vMPC` directory from https://github.com/izzyreal/vmpc-home-dir in in your `~`.

**Comment by dromer** [comment]
First test-run seems to work alright! (amd64)

Now to rtfm on how an mpc2000 works again :#

**Comment by izzyreal** [comment]
Precompiled binaries are now listed on [izmar.nl in the Downloads section](http://izmar.nl/index.php/downloads).

I've added a fix for auto-generating ttl files. If you want to build VMPC2000XL yourself, the below should work.

1. If you've built VMPC2000XL before, `rm -rf ~/.conan/data/juce`
2. If you haven't built it before, `conan remote add bintray-izmar https://api.bintray.com/conan/izmar/izmar-conan-dev-bintray`
3. `git clone https://github.com/izzyreal/vmpc-workspace && cd vmpc-workspace`
4. Uncomment [invokation of `cmake --build ./Release --config Release --target vmpc2000xl_LV2` in `build.py`](https://github.com/izzyreal/vmpc-workspace/blob/d10bab9aeb08ca2822c9d1a6a281814dd6722872/build.py#L95)
5. `python3 build.py -c ninja-single`

**Comment by KottV** [comment]
This is great news!
(I apologize for not being active on this topic.)

**Comment by izzyreal** [comment]
Resolved by https://izmar.nl/index.php/release-candidates and https://github.com/izzyreal/vmpc-binaries/tree/master/linux

**Comment by dromer** [comment]
Er, that repo only contains x86 for ubuntu 18.04 and and arm64 for ubuntu 20.04

Also: why put binaries in git? please don't. this is what build artifacts are for!

**Comment by izzyreal** [comment]
> Er, that repo only contains x86 for ubuntu 18.04 and and arm64 for ubuntu 20.04

What should it be according to you?

> Also: why put binaries in git? please don't. this is what build artifacts are for!

Feel free to contribute by improving things. I can give you permissions where required.

**Comment by dromer** [comment]
Well it's not x86 it's x86_64 (also known as amd64) and how relevant are separate 20.04-only arm64 builds? (they seem a bit outdated I think?)

Thing with putting binary files in git is that git is meant for source (text) files. A binary file mutation means the history of the repository grows enormously on each release. This is what build artifacts are for, as a way to distribute files in your repository without people having to git clone an entire repository :)

I haven't been able to build vpmc in a while, will see if I can find time to try again.

**Comment by falkTX** [comment]
if you push binaries to the repo, they will be there forever as objects (for the git history).
this makes the size of the repo grow exponentially.

See https://github.com/jatinchowdhury18/KlonCentaur/issues/35 for the exact same discussion.
basically, placing binary files on a git repo is a terrible practice.
please try to avoid it, thanks.

**Comment by dromer** [comment]
In this case it's an entire project/repository dedicated to spreading binary files. This should not be needed at all.
You can upload the artifacts right here on this project with each release.
(or of course have your CI pipeline, once there is one, take care of it)

**Comment by izzyreal** [comment]
* For the binaries in the `vmpc-binaries` git repo I've created https://github.com/izzyreal/vmpc-juce/issues/27
* I have removed the ARM64 builds from `vmpc-binaries` and references to it from https://izmar.nl
* I have renamed instances of x86 to x86_64
