### ISSUE TITLE
MacOS Crash on Band B/C/D pad pressing

### ISSUE THREAD

**Issue by michaelmon1203** [izzyreal/vmpc-juce#43]
Mac Big Sur Standalone

1. switch to bank b/c/d
2. hit keypad for pad pressing

crash sometimes, haven't import any sound on bank b/c/d yet.

**Comment by izzyreal** [comment]
This one should also be fixed for 0.4.4. Please confirm.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/commit/472a9ea28728758dfa2acff275db2d90b270614d

**Comment by michaelmon1203** [comment]
Tried it, did you block B/C/D bank lol

**Comment by izzyreal** [comment]
I really tried to fix it 😅 I just realized the correct fix is part of the commit I linked ("Resolved in ..."), but it's not part of the v0.4.4 build. Looking into this as we speak.

**Comment by izzyreal** [comment]
Updated the installer, now it should really really work 😄 https://github.com/izzyreal/vmpc-juce/releases/download/v0.4.4/VMPC2000XL-Installer-Intel-M1.pkg
