### ISSUE TITLE
MacOS display contrast can't be saved, always jump back to what it was.

### ISSUE THREAD

**Issue by michaelmon1203** [izzyreal/vmpc-juce#45]
Mac Big Sur Standalone

1. Change tap count to 3
2. Change display contrast to high
3. close vmpc
4. open vmpc, continue session

Display contrast not saved

**Comment by izzyreal** [comment]
"Others" screen persistence fixed here https://github.com/izzyreal/mpc/commit/acb94e0fe2a9522589a1c7b08154b66cfbc3e7dc
Contrast rendering fixed here 429f4975ca086874128a002d202d7b269e9e0786
Will be part of v0.4.5 but if you need it earlier just let me know.
