### ISSUE TITLE
MacOS can't save as type Copy Operating System

### ISSUE THREAD

**Issue by michaelmon1203** [izzyreal/vmpc-juce#47]
Mac Big Sur Standalone

1. shift+enter
2. nav to save type [Copy Operating System]
3. hit Do It

no response.

**Comment by izzyreal** [comment]
Considering VMPC2000XL doesn't have an operating system of its own, I have removed the option altogether here https://github.com/izzyreal/mpc/commit/1165eaa59a46d88cc2bb6b6155b1cd9d2efbeae6

**Comment by izzyreal** [comment]
@michaelmon1203 Many thanks for reporting all these issues!

**Comment by michaelmon1203** [comment]
any method we can talk outside of GitHub? I'm running a YouTube channel called 「playpm」, planning to make a shout out video for your work, let's get in touch!

**Comment by izzyreal** [comment]
@michaelmon1203 That's awesome! You can message me at info at izmar dot nl

**Comment by izzyreal** [comment]
It's an email addess. I have no IG.

**Comment by izzyreal** [comment]
![image](https://user-images.githubusercontent.com/3707432/168824729-fff63b3b-0ffa-43a7-9b9b-d459e7c1a82c.png)
