### ISSUE TITLE
Note Off events are missing in latest master

### ISSUE THREAD

**Issue by deviant-syndrome** [izzyreal/vmpc-juce#58]
Environment: macOS Catalina 
Built from sources using XCode toolchain

Seems like the when running, sequencer forgets to produce noteOf MIDI events in the MIDI output
NoteOFF events are sent properly in the latest 0.4.4. release 

Steps to reproduce: 
1. Go to settings and set MIDI output to some observable MIDI sink (IAC Driver can be used for that on Mac)
2. Set the track device to 01 / channel 01A
3. Input some notes in step mode 
4. Press play
5. Attach any MIDI monitor and see that only noteON MIDI events are produced, and no noteOFF
6. Notice, that pressed pads always stay highlighted

Possibly, related to these [changes](https://github.com/izzyreal/mpc/commit/e47384042b67de3cbba6b860902d3689d03a7322)
Thank you

**Comment by izzyreal** [comment]
Good catch! I'll keep you posted.

**Comment by izzyreal** [comment]
Let me know if this covers it: https://github.com/izzyreal/mpc/commit/3537331cdeff009cef437a158c620f3db2ee525d

**Comment by deviant-syndrome** [comment]
Well, with this change alone, it still does not work.
I poked around a bit through debugger and found out the following:
* The code you added to the `mpc` lib is executed, however the duration there is always `-1`
Seems, like this is related to [voice overlap check](https://github.com/izzyreal/mpc/blob/3537331cdeff009cef437a158c620f3db2ee525d/src/main/audiomidi/EventHandler.cpp#L124) earlier in the same method:

If I invert the logic there like this:
```cpp
                    auto duration = voiceOverlap != 2 ? ne->getDuration() : -1;
```
it works for me, note off are coming through and pad highlights blink as intended.

Hope this helps. Thank you!

**Comment by izzyreal** [comment]
Ah yes, you're totally right. I tested it locally in a slightly different commit before pushing it. The fix may have to be a little bit different if we want voices to last as long as they should with regard to POLY/MONO/NOTE OFF, if I recall correctly that is. Will take another look tonight.

**Comment by izzyreal** [comment]
I just force-pushed what is the fix I intended to push yesterday 😅 You may have to remove `vmpc-juce/editables/mpc` (or do some git-fu there, whatever you prefer) for the force-pushed commit to come up.

**Comment by izzyreal** [comment]
No, thank you for being on top of this! Would have taken a while for me to notice this bug.
