### ISSUE TITLE
MIDI Clock Output severe jitter

### ISSUE THREAD

**Issue by deviant-syndrome** [izzyreal/vmpc-juce#59]
Environment: macOS Catalina
Built from sources using XCode toolchain
Standalone Application Issue

Seems, like MIDI ticks sent from sequencer are transported to target MIDI out with some irregularities. 

Steps to reproduce:
1. Run standalone application
2. Select some MIDI-bridge for MIDI output (IAM driver bus works on MacOS)
3. Make sure Sync Out is set to MIDI Clock
4. Create a 1 bar sequence
5. Add 16 copies of this sequence to a song, thus have 16 bars of signal
6. Run any DAW, make it sync to external clock. Use the MIDI out of VMPC as MIDI Clock source
7. Run the song on MPC
8. The sequence will play 16 bar and stop. VMPC sequence will stop at 017.01.00
9. Notice, that DAW bar counter would stop at around 017.01.30, meaning that the clock was lagging

This jitter is clearly audible, when you, for example sync some VST arpeggiator or drum machine to Standalone VMPC.
After about 6 bars, they start to drift. 

To eliminate the possible influence of third-party MIDI bridge to clock jitter, I also tried to sync, using a DAW (Reason) as a clock source through the same pipeline. It was rock solid. 

According to the code, MIDI out is produced via an advanced concurrent non-blocking queue, which is "block-free", but not "wait free" or something. So, probably, MIDI Clock should be sent via separate high-priority pipeline.

P.S. I completely understand, that 
* This is a very rare and peculiar use case
* The problem with clock jitters in electronic music is ubiquitous and there is no way this could be prioritised above any other feature
* Could be a problem specific to MacOS

I can try my hand at cobbling something together on this topic, if you could give me any hints, where I should start digging. 
Or we can just close this issue as "won't fix" if this is too overwhelming. 

Thank you.

**Comment by izzyreal** [comment]
And to be sure, are you running the Release build?

**Comment by izzyreal** [comment]
Ah never mind, I tried it and it doesn't help. I'll work on it. But please take a look if you can. I think it may be related to how there is no synchronization between the continuously emitted clocks in `MidiClockEmitter` running on the audio thread, and the moment you start playing a sequence due to some keyboard or mouse input off the main thread.

**Comment by izzyreal** [comment]
Update: Looked into this a bit, will require quite a bit more thought and effort. I hope to get to a proper fix soon.

**Comment by deviant-syndrome** [comment]
Hey. Thank you for looking into this. 

Not sure, if this is any help, but I decided to provide a more accurate picture of MIDI Clock jitters here. 

MIDI Clock is 24 ppq, meaning that for 120BPM tempo, the duration between pulses should be around 20,8(3) ms. I quickly put together a simple MaxMSP patch to measure the actual pulse lengths produced by VMPC. This paints a bit of disturbing picture. I have no idea where did those 10ms intervals came from. 

![MIDI Clock VMPC Original](https://user-images.githubusercontent.com/86923754/213642126-3c374a19-a800-4d68-a252-a73f6074d84a.png)

For comparison, on the same setup I used Reason DAW to send MIDI clock, and I got much more stable results. 

![MIDI Clock Reason DAW](https://user-images.githubusercontent.com/86923754/213642145-c5cb4b05-c7f6-4ecf-9def-b020e3ecc187.png)

Also, what I've noticed from the code, it seems, that there are actually 2 separate places, from where we are sending MIDI clock events. 
One is in [EventHandler](https://github.com/izzyreal/mpc/blob/master/src/main/audiomidi/EventHandler.cpp#L84), where, I guess, those are generated from the sequencer's clock events (did not find the place, where they are put into the sequence, though)
Another is [MidiClockEmitter](https://github.com/izzyreal/mpc/blob/master/src/main/audiomidi/MidiClockEmitter.cpp#L24), that is also sends MIDI event directly to outputs, but it is driven by internal clock which is ticking at 96 ppq!

**Comment by deviant-syndrome** [comment]
Hey! Ok, at least, MIDI clock handling process within the VMPC is a bit more clear to me now. 

Regarding enqueuing MIDI start before next MIDI tick makes sense to me, as it seems to be compliant with the standard. So, that should be the right thing to do. 

In terms of my experience with syncs, I had quite the opposite, it starts steady, but then they deviate. 
To explore even further, I also plotted the graph that shows VMPC's MIDI clock pulse length. What I see, is that this clock drop-outs to ~10ms happen over equal periods of time. Strange. 

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/86923754/214086747-8faaebe1-be49-4252-bee1-460b12c199e1.png">

**Comment by izzyreal** [comment]
I think I found the main culprit for the jitter. JUCE is by default not configured to use the highest precision that it can for MIDI out in standalone.

You can call `startBackgroundThread()` against a MIDI-output to enable a high-precision timer thread for it. The easiest way to hack it into JUCE for experimentation is by adding `defaultMidiOutput.startBackgroundThread()` after this line: https://github.com/juce-framework/JUCE/blob/e49fb38d44622435f39f486530e84f84df20c8af/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp#L1204

You will see that without this background thread the precision is tied to the buffer size. Smaller buffer sizes give higher precision than bigger ones. By enabling the background thread, I found the precision becomes independent from buffer size.

Additionally I made this "reference implementation": https://github.com/izzyreal/juce-sync-test
It only plays a metronome (press any key to start/stop) and sends MIDI start/stop and clock.

If we can get the reference implementation to perform as desired, after that we can make VMPC2000XL congruent with that performance.

**Comment by izzyreal** [comment]
When you have time, can you create a histogram for https://github.com/izzyreal/juce-sync-test like you did earlier for VMPC2000XL? I'm curious if it matches the distribution you got from Reason.

**Comment by deviant-syndrome** [comment]
Yes, sure. I'll try to do this in the following couple of days.

**Comment by deviant-syndrome** [comment]
Good news. 
I used the reference implementation to measure the pulse length of MIDI clock, here is what I concluded:
1. With the `juce_AudioDeviceManager.cpp` left intact, I observed pretty much the same picture with regular dropouts to 10 ms. _However..._ 
2. If I add the `startBackgroundThread()` as you recommended, it shows quite a remarkable pulse length stability. 

![image](https://user-images.githubusercontent.com/86923754/215024685-089fb20b-b264-476b-8011-3d7f5a2cbd11.png)

So far, even better than Reason, probably because reference implementation is minimal and does not have any DAW-overheads. 


I also tested MIDI transport functionality along with the clock on a VST sequencer. VST sequence plays in sync with the reference implementation's metronome without any noticeable problems. Transport works correctly as well. 

Thank you!

**Comment by izzyreal** [comment]
Very cool 😃 I'll try to wrap up a PR soon to get VMPC2000XL to perform the same. Most likely it will be a combination of changes to `mpc` in tandem with `vmpc-juce`. Thanks again!

**Comment by izzyreal** [comment]
Please check the `midi-sync` branch on `mpc` and `vmpc-juce`, where I've integrated the changes that should make it perform like the reference implementation. I'm getting not so terrible results syncing to Ableton Live, see the video.

https://user-images.githubusercontent.com/3707432/215333450-573216dc-704b-4d83-9c5a-8e3fb1d4ec5c.mov

There are 2 pull requests:
https://github.com/izzyreal/vmpc-juce/pull/61
https://github.com/izzyreal/mpc/pull/124

The diff is not very hygienic, sorry for that. I came across some slightly related clean-up.

**Comment by deviant-syndrome** [comment]
Aaaaalright.... 
So, MIDI clock is quite solid now. 

![Screenshot 2023-01-31 at 9 12 11](https://user-images.githubusercontent.com/86923754/215698309-cf2b0983-cee0-4353-9427-b6f371587005.png)

Also, MIDI transport and arpeggiator lock seems fine to me as well. Please, don't pay attention to arpeggiator position moving out of sync with the sound, this is just a desktop recording issue. 


https://user-images.githubusercontent.com/86923754/215698511-39454a79-4103-43c7-8423-235811de3ac6.mov


I skimmed through the PRs code, I generally agree with the elaborate logic of the new FrameSeq. Do not know, if I can provide you with the full code-review, though, as my C/C++ audio DSP expertise is quite limited. 



Seems, once those PRs are whipped into shape and merged, this issue can be closed
Thank you very much for all the work you've done on this topic.

**Comment by izzyreal** [comment]
Funky jam in your video 🤘 
Thanks for skimming the PR and taking more measurements! What do you mean by "whipped into shape"? I was going to merge them as is, so if you noticed anything odd let me know.

**Comment by deviant-syndrome** [comment]
Heh. Thank you. 
Yeah, by "whipping into shape" I mean some purely cosmetic improvements, I added them as comments to the PRs, but feel free to disregard, of course, really minor things.  

Again, not really eligible to comment on the code quality here, so I would assume, it's good. 
Thanks, again

**Comment by izzyreal** [comment]
Good catches in the comments I've seen. I'll whip it into shape and merge!

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/pull/125 and https://github.com/izzyreal/vmpc-juce/pull/61
