### ISSUE TITLE
Crash when navigating sound folders

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#70]
I'm experiencing a crash across different systems after I have loaded a sound on the LOAD menu.

1. A sound is selected and loaded via the LOAD menu and assigned to a pad.

2. Attempting to browse the folders again to load another sound results in a crash.

This can obviously be sidestepped by dragging-and-dropping the sounds, but it's still worthy of note if this hasn't been documented.

**Comment by izzyreal** [comment]
Can you reproduce the issue reliably with the steps you have provided? It's not flaky?

**Comment by brownounces** [comment]
I can reproduce it every time. It happens on Windows 10 and Windows 11, with the latest v0.5.0 release.

Specifically, I am: 

1. Loading a sound
2. Assigning it to a pad automatically
3. Re-opening the folder browser window
4. Backing out of the previous selected folder -- this is where it crashes for me.

**Comment by izzyreal** [comment]
To make sure we're on the same page, see if you can reproduce it with this dev build: https://drive.google.com/file/d/1fX5Qehhfb518jrIaBWFyH4vfgkxvM8re/view?usp=sharing.

If no, problem solved 😄 If yes, we could begin by examining the directory contents of your `~/Documents/VMPC2000XL/Volumes/MPC2000XL`. Can you email me a zip file of that directory? Alternatively you could quit VMPC2000XL, remove everything from said directory, and start VMPC2000XL. It should automagically add back `DEMOS/TEST1` and `DEMOS/TEST2`. See if you still have the probem there.

The first possible cause that comes to mind for this issue is special characters in the file names. Another possible cause is too long file names, but as far as I know VMPC2000XL renames all content of said directory to match what is possible in the real MPC2000XL (i.e. max 16 letter file names, and max 8 letter dir names).

**Comment by izzyreal** [comment]
I just discovered that VMPC2000XL on Windows doesn't deal well with long directory names (over about 20 characters). Do you have any of those?

**Comment by brownounces** [comment]
I'm at work right now; I'll test that dev build and send you those ASAP! If you'd like to imitate what I have in there right now though, I have the default DEMO folder and another alongside it named "SAMPLES" with the [original MPC2000XL sample kit](https://archive.org/details/MPC2000XLComplete) as the content.

It could certainly be that those sample names are conflicting with some Windows gobbledygook, but the names do appear to be formatted correctly in the VMPC2000XL file browser. Maybe I should try renaming them to something shorter and simpler

**Comment by izzyreal** [comment]
The mentioned dev build URL is now obsolete. Here's the new dev build: https://drive.google.com/file/d/1-2HSVfiXj_jIH_4mJeiWGZ3zWnNWNW12/view?usp=sharing

**Comment by brownounces** [comment]
Using the latest dev build on Windows 10, it seems as though the crashing still persists. BUT, I think I've possibly isolated the problem.

I created a new sample folder with 8 subfolders of only the types of sounds I typically use and there was no crashes (though occasionally, it will get locked on the 'Playing *.wav' screen if the PLAY function is triggered after the sound is loaded -- this might require a new thread though). When I imported my complete sample library full of 20+ different subfolders, it crashes every time I attempt to navigate the file browser again after loading a sound. Perhaps it is not naming convention but the quantity of folders, quantity of samples, or file size which is causing the crash. My new sample folder also only consisted of 16-bit mono .wav files I summed from stereo tracks and converted in Audacity, compared to the hodgepodge of different formats and bit-rates in my full library.

**Comment by izzyreal** [comment]
Sounds like you're still running the previous build. Try uninstalling first (maybe even manually by just removing the executable from Program Files/VMPC2000XL).

**Comment by brownounces** [comment]
The version I have listed as installed was the v0.5.0.3 if that's the right one, from the link provided above. I made sure to uninstall the old version and manually remove any leftovers from AppData, Documents and Program Files. I'll throw more stuff at it and see if I can determine the exact cause.

**Comment by izzyreal** [comment]
All recent builds have v0.5.0.3 😅 There's currently no way to distinguish different builds if they have the same version number.

**Comment by izzyreal** [comment]
If the executable is gone before installing, that should do the trick.

**Comment by brownounces** [comment]
So I've confirmed I'm using the latest dev build, and the file manager does still crash under the same conditions for me. Sometimes simply browsing the directory crashes it, but it is consistently reproducible when loading in a sound, and then opening the directory again and exiting from the current folder. The only new observation I have is that incompatible samples are given what appear to be random letters for names and no longer have a PLAY option in the directory menu.

However, with a relatively minimal directory containing optimized samples (16 bit mono, basic and short file names, and much fewer folders) the crash does not happen. I can't pinpoint what the exception is, or if it's maybe a corrupt sample on my end causing the crash.

**Comment by izzyreal** [comment]
I lost track 😅 Can we close this one or is it still an issue?

**Comment by brownounces** [comment]
I haven't had any problem since you issued the dev build addressing it via e-mail -- that's my bad, I should have posted a reply here as well confirming it. It seems any issue regarding filenames and their related crashes has been fixed, but if anything else pops up, I'll issue a new report.

**Comment by izzyreal** [comment]
Great news! Thanks for the confirmation.
