### ISSUE TITLE
Crackle from .SND conversion

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#78]
It appears that some samples may have a crackle imparted on them upon saving them as .SND files and reloading the .PGM or .APS that they're contained in. I don't know if this is an issue with the implementation of this feature or a fundamental flaw with the .SND format itself -- in which case, it may not be fixable.

The steps I took to recreate this issue persisted across different computers and remakings of the beat in question.

1. Record this sample into the SAMPLE function of VMPC: https://www.youtube.com/watch?v=2-xxlcxZ-ME -- 0:00 - 0:10

2. Normalize the sample

3. Chop the first four notes into 4 sections using the ZONE function

4. Optionally, I tuned it down 2 semitones (-20 TUNE)

5. Optionally, I played the sample at 135 BPM; one note on every bar

6. Save all programs w/ sounds to an .APS file

7. I saved all songs and sequences (.SEQ file)

8. Upon reloading the respective .APS and .SEQ files, a crackle or pop is imparted into sound2 (the first chop from the sample)

I don't know what qualities this sample has which creates this artifact, but it is presumably not limited to this sample alone (though I can't say that it has affected any other samples I've saved), though it certainly only exists after saving and being converted to .SND

To me, this is a minor issue (a little bit of snap crackle and pop has never hurt a sample in my opinion), but I know Izzy would like to figure out the origin of it and if it is fixable.

**Comment by izzyreal** [comment]
Shares cause with https://github.com/izzyreal/mpc/issues/173.
