### ISSUE TITLE
Critical failure on ASSIGN feature

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#79]
After countless hours of trial, I have found a critical failure regarding the ASSIGN button on VMPC2000XL. This bug may render VMPC2000XL unusable.

Above the NOTE VARIATION slider, the ASSIGN button is labeled "ASSSIGN" with an entirely erroneous extra S in the spelling. Someone with OCD may not be able to continue using this software if they detect it.

It is likely fixable by removing an offending S, but it may risk breaking the program. You might need to restart this project from scratch.

**Comment by izzyreal** [comment]
🤣 Good catch

**Comment by izzyreal** [comment]
Fixed on `vmpc-juce` master. I also put an easter egg in `mpc`.
