### ISSUE TITLE
Mixer displays wrong pad bank

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#85]
A minor issue, but can sometimes lead to some confusion if you don't notice the behavior.

When opening the MIXER feature, it will almost always erroneously display the 'A' bank, even if user is currently on bank is B, C, or D. This in itself isn't a big problem, but often times changes will be made to the currently selected bank despite displaying 'A' on the MIXER.

Steps to reproduce:
1. Put some sounds on BANK A and BANK B
2. (Optional) Record a bar playing the sounds and have it on loop; this just makes it easier to track if the correct BANK is being modified in the MIXER
3. Press the BANK B button, though any of them will produce the same effect
4. Press the MIXER button, it will likely display 'A' as the current bank. This is actually okay in itself; but changing the amplitude of the pads will reveal that it is in fact modifying BANK B despite displaying A.

I can't remember how the original 2000XL handled this; I think it always displayed the bank you had selected upon pressing MIXER, rather than automatically opening A. In either case, it should be fixable by displaying the current bank when MIXER is pressed, OR by opening A and making it correspond with the A bank, from which the user can switch to the bank they want to mix after.

**Comment by izzyreal** [comment]
Good catch 👍 
Resolved in https://github.com/izzyreal/mpc/commit/7e502f5df027f40a24ac5f416ebe0242f9f24b76.
