### ISSUE TITLE
Partitions / file directory problem

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#90]
The Linux version VMPC2000XL will abort when attempting to access a folder containing sounds using the built-in file browser if /tmp (where VMPC temporarily copies sounds likely to be needed in memory?) is mounted on a different partition than the 'Volumes/MPC2000XL' folder (normally at ~home/Documents), due to an apparent access violation. This means that anyone with their /home directory on a separate partition (as is common on many Linux setups) will end up crashing when trying to access sounds.

It may be possible to fix this by allowing the user to set the location of VMPCs temporary folder so it is on the same partition as the user's sound library.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/commit/728f2153cee246a885498b4d69c19e31a546e033
