### ISSUE TITLE
Resizing in Ardour (Linux) can result in displaced Components

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/vmpc-juce#92]

**Comment by brownounces** [comment]
Here is some screenshots of the problem: https://imgur.com/a/YqzBbRz

The animated components will become misaligned when trying to arbitrarily resize the plugin window in Ardour (and possibly other DAWs). This issue can be 'fixed' by readjusting the width of the window until the components are aligned back in their space (third image).

The standalone version of VMPC has a fixed aspect ratio which keeps these components in alignment -- I think some DAWs override this forced aspect ratio, breaking the offsets of the animated knobs.

**Comment by izzyreal** [comment]
Can you try with https://github.com/izzyreal/mpc/commit/25c74bfc744ffdc04869f860c7fe1649a0a3cc5b ?

**Comment by izzyreal** [comment]
Sorry, I meant with 1c7733372a639134822ec4667ba960d4366c2ddd

**Comment by brownounces** [comment]
Going to check in Ardour tomorrow and I'll let you know for sure.

**Comment by brownounces** [comment]
> Going to check in Ardour tomorrow and I'll let you know for sure.

Confirming this is now fixed! The ratio holds no matter how you try to resize the window.
