### ISSUE TITLE
List of Linux dependencies missing

### ISSUE THREAD

**Issue by MushiTheMoshi** [izzyreal/vmpc-juce#94]
Hi there,

First of all, appreciate all effort done here, it looks amazing.

I have problems to build the repo, seems that I may be missing some dependencies, could not find a list of dependencies, is it possible to include them in the readme?

Thanks in advance!
Julio

**Comment by izzyreal** [comment]
Thanks for the feedback @MushiTheMoshi ! What OS are you using and what kind of build errors do you get?

For what it's worth, I've just added the `Dockerfile` I use for building Ubuntu binaries to the README: https://github.com/izzyreal/vmpc-juce/commit/2cdacfe40eb933c9f67c27e85aa0e2677b92a895.

**Comment by MushiTheMoshi** [comment]
Hi there,

Thanks for your prompt response!

I am using linux ubuntu 22.04 , I will check that file. I am not near my computer, will post later the error.

Thanks again!

**Comment by izzyreal** [comment]
Gonna close this due to inactivity. Feel free to reopen if you encounter any issues.
