### ISSUE TITLE
[bug] No key repeats in Linux

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#95]
It appears that the data wheel (or jog wheel) does not continue to move when its hotkey is held down; it works for a single action and then stops. I'm not sure which version introduced this behavior.

Perhaps this was never an intended feature, but using the data wheel in combination with shift made sample slicing super quick compared to clicking the data wheel and dragging it around. If possible, perhaps it could be reintroduced as an option if it was intentionally made to function in this new way.

**Comment by izzyreal** [comment]
@brownounces Please try this version https://drive.google.com/file/d/1lfw6VLxhMlyF2-wYibiw-MrhMo6agjpt/view?usp=sharing

It has hardcoded values for:
```
        const int keyrepeatDelay = 400; // ms
        const int keyrepeatInterval = 25; // ms
```

So I hope they work well for you 😃

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/juce-raw-keyboard-input-module/commit/eb10727720b954cbf6dd29784e605755c7ad0132
Will be part of the next release (0.5.8).
