### ISSUE TITLE
Dragging and dropping sounds on Wayland (Linux)

### ISSUE THREAD

**Issue by brownounces** [izzyreal/vmpc-juce#96]
Perhaps not a VMPC problem itself, but I noticed that dragging and dropping sounds onto the VMPC pads does not work when using Wayland. Of course, the obvious solution is to just use Xorg, but it may be valuable to 'futureproof' VMPC should Xorg ever become truly deprecated.

This is possibly a feature of Wayland's security-focused GUI isolation; it may be worth while to devise a workaround that allows this feature to exist on Wayland should distros ever stop shipping Xorg.

**Comment by izzyreal** [comment]
I don't think the fact that you're using Wayland is the root issue. See our email convo with subject "Linux notes" started on 21 May, my first reply. Seems technically possibly to use drag and drop in Wayland, but there may be some conditions.

Not sure how much work it is for you, but it would be great if you could verify on a clean Ubuntu Wayland VM. You could use the v0.5.1 binaries I [published a few days ago](https://izmar.nl/downloads).

If drag and drop works well there, and if you can provide steps to reproduce starting with a clean ISO of a distro of your choice (you're on Gentoo iirc), I may be able to diagnose.

**Comment by izzyreal** [comment]
@brownounces Going to close this due to inactivity. Feel free to reopen at any point.
