### ISSUE TITLE
Unable to use Convert in Song mode

### ISSUE THREAD

**Issue by c3ntr0n800** [izzyreal/vmpc-juce#98]
When I was learning how to use the 2000XL through a tutorial on YouTube, I noticed that the Convert function doesn't seem to do anything. While I ended up just copying and pasting the notes to another bar myself, it would be nice to have this in the emulator too.

**Comment by izzyreal** [comment]
Good call @c3ntr0n800, I'll try to prioritize this.

**Comment by izzyreal** [comment]
Duplicated by https://github.com/izzyreal/mpc/issues/112

**Comment by c3ntr0n800** [comment]
Oh my bad, I didn't know you already had this issue opened on the other repo. I forgot to look there before opening up one here.

**Comment by izzyreal** [comment]
@c3ntr0n800 No worries, I'm glad you reported it 👍
